name: expenzo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/app_icon.png
  android_12:
    image: assets/icons/app_icon.png
    icon_background_color: "#FFFFFF"
  ios: true
  web: true
  android: true
